---
version: '3'
services:

  daemon:
    build: .
    environment:
      IMAP_URL: ${IMAP_URL}
      WEBHOOK_URL: http://mock:5000/
      ON_SUCCESSS: 'delete'

  mock:
    build:
      context: mock
    ports:
      - 5000:5000