---
name: Python application

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull python image
        run: docker pull python:3.10-slim
      - name: Build app container
        run: docker compose build daemon
      - name: Run app container
        run: docker compose up -d daemon
      - name: Show app directory
        run: docker compose run daemon ls -la
      - name: Add git safe directory
        run: docker compose run daemon git config --global --add safe.directory /usr/src/app
      - name: Show git status
        run: docker compose run daemon git status
      - name: Ceck code style
        run: docker compose run daemon pre-commit run --all-files
      - name: Run tests
        run: docker compose run daemon python test.py
