---
name: Python application

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull python image
        run: docker pull python:3.10-slim
      - name: Build app container
        run: docker compose build daemon
      - name: Run app container
        run: docker compose up -d daemon
      - name: Show app directory
        run: docker compose run daemon ls -la
      - name: Ceck code style
        run: make code-syle-check
      - name: Run tests
        run: make test
