---
name: Python application

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Pull python image
        run: docker pull python:3.10-slim
      - name: Run tests
        run: make test
